### ISSUE TITLE
您好，请问json是如何生成的

### ISSUE THREAD

**Issue by chen-bh** [wangtianrui/DCCRN#12]
您好，我跟着 https://github.com/ShenYi666666/DNS-Challenge 把数据下载完了。也生成了一批数据（也是这个git的代码）。但是我没有找到 json文件。请问是为啥呢。

如果必须下载2022年的数据（太大了）；请问数据集或者说json文件的规则是怎样的；我自己撸代码搞一批。

找到的资料比较少，看不出个所以然；望不吝赐教。

**Comment by wangtianrui** [comment]
Json文件的生成规则：整体是一个字典数组，每个Item里有 mix：加噪后的语音路径；clean：干净语音路径；noise：噪声路径。
你如果按照DNS官方脚本生成了数据的话，会得到noisy、clean、noise三个文件夹。他们内部的语音是根据file_id对应起来的。你可以根据这个id来生成对应的json。

**Comment by chen-bh** [comment]
一语惊醒梦中人；原来官方只靠末尾id来一一对应。。。非常感谢。

**Comment by chen-bh** [comment]
作者大大您好，我跑通了您的代码（除了因为版本问题，替换了几个函数；使用的是默认参数训练）。

训练的时候他2个小时一个epoch有点恐怖(1080Ti)；我看显存是占满了的，利用率也在有规律浮动。

请问2个小时一个epoch正常吗。

**Comment by wangtianrui** [comment]
你的数据量是多少。我当时生成了100小时的数据。用两张P100（16G显存）跑了两周才跑完的。
如果你嫌慢的话，我建议：
1、你可以减小语音长度（比如减小到5s）来增大batch的大小，以加快BatchNorm的收敛。
2、把信噪比控制在 -5 到 20dB，不要像我之前一样去生成 0 到 40dB的数据，我实验发现 -5 到 20dB 50小时的数据和 0 到 40dB 100小时的数据训练出来的模型效果是差不多的。

**Comment by chen-bh** [comment]
明白了，祝周末愉快。
