### ISSUE TITLE
Hello, I have a question about dataset

### ISSUE THREAD

**Issue by e349808405** [wangtianrui/DCCRN#2]
Can you tell where I can find the dataset, I find the dataset from "https://github.com/microsoft/DNS-Challenge/tree/master/datasets", but the file of dataset is too big. Are you simplifying the dataset? Thank you very much if you canm answer

**Comment by wangtianrui** [comment]
the dataset that i used in this code is [DNS-Challenge](https://github.com/microsoft/DNS-Challenge).You can download it by following the steps provided by the authorities.

If this dataset is very big for you.You can try a smaller dataset:[Valentini dataset](https://datashare.is.ed.ac.uk/handle/10283/2791)

or you can generate your own datasets by  the [DNS-Challenge code](https://github.com/microsoft/DNS-Challenge/blob/master/noisyspeech_synthesizer_singleprocess.py)

**Comment by e349808405** [comment]
thank you very much, I will have a try.
