### ISSUE TITLE
download DNS dataset

### ISSUE THREAD

**Issue by wangtao2668129173** [wangtianrui/DCCRN#3]
Hello, I tried to download the data set using the official method, and I also tried to download the data set through "wget", but the data was not available, code show as below:
 for root,dirs,files in os.walk(args.datasetpath):
        wav_files = []  
        path = "https://github.com/microsoft/DNS-Challenge/tree/master/datasets"
        for line in files:
            if line.endswith(".wav"):
                wav_files.append(os.path.join(root,line))
            else:
                pass
        for file in wav_files:
            URL = path+file[37:]
            cmd = "wget -p " +file+" "+URL
            os.system(cmd)

**Comment by wangtianrui** [comment]
#2 Please refer to the answer to this question. Thanks.
