### ISSUE TITLE
AttributeError: can't set attribute

### ISSUE THREAD

**Issue by ermu-tech** [wangtianrui/DCCRN#4]
你好，我安装了torch==1.6.0和asteroid==0.3.4，我的cuda版本为10.2，但是在运行train.py文件的时候报错：AttributeError: can't set attribute，具体报错如下：
Traceback (most recent call last):
  File "/media/li/TOSHIBA EXT/WDCCRN /DCCRN-master/train.py", line 21, in <module>
    my_system.init_system_and_trainer(SystemClass=MySystem, model=model_, gpus=[0])
  File "/media/li/TOSHIBA EXT/WDCCRN /DCCRN-master/BaseModel.py", line 85, in init_system_and_trainer
    config=self.conf
  File "/home/li/anaconda3/envs/W-DCCRN/lib/python3.6/site-packages/asteroid/engine/system.py", line 58, in __init__
    self.hparams = Namespace(**self.config_to_hparams(config))
  File "/home/li/anaconda3/envs/W-DCCRN/lib/python3.6/site-packages/torch/nn/modules/module.py", line 1178, in __setattr__
    object.__setattr__(self, name, value)
AttributeError: can't set attribute
请问我该如何解决这个问题呢？

**Comment by wangtianrui** [comment]
你在 basemodel 文件里的 init_system_and_trainer 中输出看一下self.conf呢

然后你把 pip list发出来看一下。以及python版本。我这边用的是python3.6

**Comment by ermu-tech** [comment]
我在basemodel 文件里的 init_system_and_trainer 中第85行config=self.conf语句处打了断点，debug到这一步的时候self.conf的值是正常的，再step into之后就会提示{AttributeError}'MySystem' object has no attribute 'conf'，下面是我的报错截图和pip 
![2021-06-25 17-20-36屏幕截图](https://user-images.githubusercontent.com/58473058/123402945-dc449100-d5da-11eb-8f14-daf1466f5266.png)
![2021-06-25 17-21-48屏幕截图](https://user-images.githubusercontent.com/58473058/123402965-e070ae80-d5da-11eb-9a6f-1ad57edd173e.png)
![2021-06-25 17-21-56屏幕截图](https://user-images.githubusercontent.com/58473058/123402979-e4043580-d5da-11eb-930e-f2803fb16640.png)
list
![2021-06-25 17-20-22屏幕截图](https://user-images.githubusercontent.com/58473058/123402748-a6071180-d5da-11eb-9cf5-75450212dc72.png)

**Comment by wangtianrui** [comment]
首先您的报错应该是asteroid库的问题。所以我比较怀疑是asteroid更新了。（因为这个项目大半年前写的，我目前已经没有用asteroid了）
其次您发的pip里我没有找到asteroid的版本。
最后，我在我的旧环境中重新运行了一下，是能够run起来的。（只需要修改一下valid_file_info.json为test_file_info.json，这个json最好根据你自己的数据重新照着格式做一遍)
![](https://z3.ax1x.com/2021/06/26/RGrhnS.png)

我给您列一下我的环境，您对照看一下（我将所有环境都列出来了，还请您自己筛选一下。)

absl-py                0.10.0
adabelief-pytorch      0.0.5
adamp                  0.3.0
aiohttp                3.6.2
appdirs                1.4.4
argon2-cffi            20.1.0
asteroid               0.3.4
astor                  0.8.1
async-generator        1.10
async-timeout          3.0.1
attrs                  20.2.0
audioread              2.1.8
backcall               0.2.0
bandmat                0.7
bleach                 3.2.1
cached-property        1.5.2
cachetools             4.1.1
certifi                2021.5.30
cffi                   1.14.3
chardet                3.0.4
cycler                 0.10.0
Cython                 0.29.21
dataclasses            0.8
decorator              4.4.2
defusedxml             0.6.0
einops                 0.3.0
entrypoints            0.3
fastdtw                0.3.4
flatbuffers            2.0
fsspec                 0.8.4
future                 0.18.2
Gammatone              1.0
gast                   0.2.2
google-auth            1.22.0
google-auth-oauthlib   0.4.1
google-pasta           0.2.0
grpcio                 1.32.0
h5py                   2.10.0
idna                   2.10
idna-ssl               1.1.0
importlib-metadata     2.0.0
ipykernel              5.3.4
ipython                7.16.1
ipython-genutils       0.2.0
ipywidgets             7.5.1
jedi                   0.17.2
Jinja2                 2.11.2
joblib                 0.16.0
jsonschema             3.2.0
jupyter                1.0.0
jupyter-client         6.1.7
jupyter-console        6.2.0
jupyter-core           4.6.3
jupyterlab-pygments    0.1.1
kaldi-io               0.9.4
Keras-Applications     1.0.8
Keras-Preprocessing    1.1.2
kiwisolver             1.2.0
librosa                0.8.0
llvmlite               0.34.0
Markdown               3.2.2
MarkupSafe             1.1.1
matplotlib             3.3.2
mir-eval               0.6
mistune                0.8.4
mkl-fft                1.2.0
mkl-random             1.2.0
mkl-service            2.3.0
mock                   4.0.2
multidict              4.7.6
musdb                  0.3.1
museval                0.3.0
nbclient               0.5.0
nbconvert              6.0.6
nbformat               5.0.7
nest-asyncio           1.4.1
nnmnkwii               0.0.22
nose                   1.3.7
notebook               6.1.4
numba                  0.51.2
numpy                  1.19.1
oauthlib               3.1.0
olefile                0.46
onnx                   1.9.0
onnxruntime            1.8.0
opt-einsum             3.3.0
packaging              20.4
pandas                 1.1.2
pandocfilters          1.4.2
parso                  0.7.1
pb-bss-eval            0.0.2
pesq                   0.0.2
pexpect                4.8.0
pickleshare            0.7.5
Pillow                 7.2.0
PinkBlack              0.0.9
pip                    20.2.2
pooch                  1.2.0
prometheus-client      0.8.0
prompt-toolkit         3.0.7
protobuf               3.13.0
ptyprocess             0.6.0
pyaml                  20.4.0
pyasn1                 0.4.8
pyasn1-modules         0.2.8
pycparser              2.20
Pygments               2.7.1
pyparsing              2.4.7
pypesq                 1.2.4
pyrsistent             0.17.3
pysptk                 0.1.18
pystoi                 0.3.3
python-dateutil        2.8.1
pytorch-lightning      0.9.0
pytorch-ranger         0.1.1
pytz                   2020.1
PyYAML                 5.3.1
pyzmq                  19.0.2
qtconsole              4.7.7
QtPy                   1.9.0
requests               2.24.0
requests-oauthlib      1.3.0
resampy                0.2.2
rsa                    4.6
scikit-learn           0.23.2
scipy                  1.5.2
seaborn                0.11.1
Send2Trash             1.5.0
setuptools             49.6.0.post20200814
shadowsocks            2.8.2
simplejson             3.17.2
six                    1.15.0
SoundFile              0.10.3.post1
sox                    1.4.1
speechmetrics          1.0
SRMRpy                 1.0
stempeg                0.1.8
tensorboard            2.0.0
tensorboard-plugin-wit 1.7.0
tensorflow             2.0.0
tensorflow-estimator   2.0.1
termcolor              1.1.0
terminado              0.9.1
testpath               0.4.4
threadpoolctl          2.1.0
torch                  1.7.1+cu92
torch-optimizer        0.0.1a15
torch-stoi             0.1.1
torchaudio             0.7.2
torchaudio-contrib     0.1
torchvision            0.8.2+cu92
tornado                6.0.4
tqdm                   4.50.0
traitlets              4.3.3
typeguard              2.12.1
typing-extensions      3.7.4.3
urllib3                1.25.10
wcwidth                0.2.5
webencodings           0.5.1
Werkzeug               1.0.1
wheel                  0.35.1
widgetsnbextension     3.5.1
wrapt                  1.12.1
yarl                   1.6.0
zipp                   3.2.0

**Comment by ermu-tech** [comment]
非常感谢您的回复！我对照您给出的环境列表作出了修改，应该是pytorch版本的问题，需要安装1.7.0，我想应该是可以跑的
现在需要对json作出修改，可以麻烦您对json文件中的语句做出一下解释吗？
比如这句 "6508": {"mix": "F:\\Traindata\\DNS-Challenge\\make_data\\noisy\\book_03549_chp_0001_reader_01297_21_B_l5G4P8tMk-2FccuV13ATg-GbGmSwkTSCo_snr34_fileid_6508.wav", "clean": "F:\\Traindata\\DNS-Challenge\\make_data\\clean\\clean_fileid_6508.wav", "noise": "F:\\Traindata\\DNS-Challenge\\make_data\\noise\\noise_fileid_6508.wav", "snr": 34, "file_len": 480000}
最前面的数字表示什么？
每个键值对中只包含一条语音吗？
“noise”文件必须要有吗？我使用的是您在其他评论中给出的较小的数据集Valentini dataset，该数据集中没有噪声文件，请问这该如何处理呢？
期待您的回复，谢谢！
![2021-06-28 21-16-39屏幕截图](https://user-images.githubusercontent.com/58473058/123645815-3f435b80-d859-11eb-881d-4c7662b83eef.png)

**Comment by wangtianrui** [comment]
哦哦  抱歉。torch版本看来后来换过。
关于json文件说明：前面的key是没有意义的。单纯用来标号的。mix是加噪数据路径，clean是参考数据路径，noise可要可不要（训练时是不会用到的）

**Comment by ermu-tech** [comment]
请问每个键值对中只包含一条语音吗？"snr"的数值所如何设定的呢？

**Comment by wangtianrui** [comment]
每一个键值对都只包含一组语音：加噪的、干净的、噪声、在合成时的SNR、语音长度。（真正参与训练的只会用到前两个信息）

SNR是在生成加噪语音时得到的。详细请参考DNS-Challenge的加噪语音制作脚本。（生成后的数据名中也会有相应的信息）

**Comment by wangtianrui** [comment]
如果没有其他问题，我将在12小时后关闭此 issue

**Comment by ermu-tech** [comment]
请问您的train_file_info.json和valid_file_info.json文件中各有几组语音呢？您在生成json文件时是纯手写的吗？还是有其他方法？（数据量有点大所以想请教一下简单方法）
还有就是我在修改了部分train_file_info.json和valid_file_info.json中的语句后，出现了以下问题，请问这是由什么引起的呢？
![Uploading 2021-06-29 17-36-18屏幕截图.png…]()

**Comment by ermu-tech** [comment]
请问您的valid_file_info.json和test_file_info.json文件中各有多少组语音呢？您在写json文件时时纯手写的吗？还是有什么其他方法？（因为数据量有点大所以想请教一下有没有简单方法）
还有就是我在修改了部分valid_file_info.json为test_file_info.json中的语句后（两个文件修改的语句数量不同），出现了以下问题，请问这是由什么引起的呢？
![2021-06-29 17-36-18屏幕截图](https://user-images.githubusercontent.com/58473058/123812044-59973b00-d926-11eb-9ab0-d300bdf278e1.png)

**Comment by wangtianrui** [comment]
json文件是你根据你自己数据的情况制作的。你可以试试python的os.walk方法来进行遍历。不是手写的。。

你的问题是输入的语音长度不同，但是pytorch的读取要求是每个批次中各个数据等长。在不改变你数据集的前提下可以参考一下语音识别系统的数据读取，对每个数据进行一个pad，补充成等长数据。

我这里是针对DNS数据集的读取，DNS脚本制作出来的数据的长度都是一致的（30s）

**Comment by ermu-tech** [comment]
可以麻烦您分享一下您制作的数据集吗？十分感谢！

**Comment by wangtianrui** [comment]
数据集很大。。你可以去参考[DNS-challenge](https://github.com/microsoft/DNS-Challenge)制作。
按照他官方的步骤把数据下载下来，然后运行他的合成代码就行。

**Comment by ermu-tech** [comment]
W

**Comment by ermu-tech** [comment]
您好，我使用wsj0中几条相同长度的语音做了测试，仍出现了以下问题，请问这是由什么造成的呢？
或者可以先分享几条您制作的数据集中的语音吗，我想先测试一下程序是否能够跑通再做进一步研究，谢谢！
![2021-07-01 10-19-39屏幕截图](https://user-images.githubusercontent.com/58473058/124056301-ff969280-da57-11eb-9684-384dc4420c73.png)

**Comment by wangtianrui** [comment]
你这还是不等长的。等长是要采样点都是一样的才行。
如果你只是想测试代码，你可以在读取后全部做一个截断就行。在dns_loader.py的第40行加：
```python
noisy, clean = noisy[:16000] , clean[:16000]
```
截取所有语音的前一秒就行。

我比较建议你多看一下代码的原理。结合你自己的情况去改代码就行。

**Comment by ermu-tech** [comment]
好的，新手上路，非常感谢您的耐心指导，我会继续努力的！
