### ISSUE TITLE
Question or Bug

### ISSUE THREAD

**Issue by shanhaidexiamo** [wangtianrui/DCCRN#7]
This line should be times rather than plus?
https://github.com/wangtianrui/DCCRN/blob/bcfccf45e2261b9b2fb13093937e6617bbe1e266/model.py#L165

**Comment by wangtianrui** [comment]
Multiplication of phases will be converted to the addition of exponents:
```txt
|S| \cdot |S|_{mask} \cdot ( e^j{\theta} \cdot e^j{\theta_{mask}} )  ->  |S| \cdot |S|_{mask} \cdot e^j{\theta +\theta_{mask}} 
```
Details can be found in the original DCCRN paper.

**Comment by shanhaidexiamo** [comment]
Oops! I got it. thank you very much.

**Comment by wangtianrui** [comment]
You're welcome.  Have a nice day!
